name: CI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    timeout-minutes: 20
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #    with:
        # submodules: recursive

      # Runs a single command using the runners shell
      - name: Compiling repo
        run: |
          make clean
          make
  
  test:
    runs-on: self-hosted

    timeout-minutes: 20

    needs: build

    steps:
   
      # Checks Histogram
      - name: Checking Histogram with 4K bins
        run: |
          ./histogram 1000000 &> 4096.out
          tail -n2 4096.out | diff .github/test/1M4096.solution -
        if: always()
        
      - name: Checking Histogram with 1K bins
        run: |
          ./histogram 1000000 1024 &> 1024.out
          tail -n2 1024.out | diff .github/test/1M1024.solution -
        if: always()  
        
  cleanup:
    
    runs-on: self-hosted
    if: always()
    needs: [build,test]
    steps:
      - name: Clean up
        run: echo "Cleaning up previous run"; rm -rf "${{ github.workspace }}";

